[package]
name = "nbhr_digging"
version = "0.1.0"
authors = ["Eiko Thomas <eiko.thomas@lisaplus.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
